version: '3'
services:
  nwserver:
    image: beamdog/nwserver:latest
    volumes:
      - ./server:/nwn/home
    env_file: ./docker/server.env
    network_mode: "host"
    ports:
      - "5121:5121/udp"
    restart: always
    stdin_open: true
    tty: true
